import { Platform, StyleSheet } from 'react-native';

export const palette = {
  paper: '#FAF8F2',
  surface: '#FFFFFF',
  ink: '#1D1A14',
  body: '#3E3A2E',
  muted: '#55503F',
  subdued: '#8F887A',
  border: '#E0DACB',
  divider: '#F1EDE2',
  control: '#F3F0E7',
  controlStrong: '#EBE5D8',
  green: '#54724F',
  targetBand: '#F0F3EA',
  goldText: '#6E5613',
  goldBackground: '#FBF0CB',
  rustText: '#8C4A2F',
  rustBackground: '#FAEBE1',
} as const;

export const serifFont = Platform.select({
  android: 'serif',
  ios: 'Georgia',
});

export const sharedStyles = StyleSheet.create({
  screen: { flex: 1, overflow: 'hidden', backgroundColor: palette.paper },
  scroll: { flex: 1 },
  header: {
    minHeight: 94,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  title: {
    color: palette.ink,
    fontFamily: serifFont,
    fontSize: Platform.select({ ios: 32, default: 34 }),
    lineHeight: Platform.select({ ios: 38, default: 41 }),
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.controlStrong,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 28,
    gap: Platform.select({ ios: 20, default: 16 }),
  },
  card: {
    padding: Platform.select({ ios: 22, default: 20 }),
    borderWidth: 1,
    borderColor: 'rgba(29, 26, 20, 0.06)',
    borderRadius: 24,
    gap: 12,
    backgroundColor: palette.surface,
    shadowColor: palette.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: Platform.select({ ios: 0.08, default: 0 }),
    shadowRadius: 20,
  },
  cardTitle: {
    color: palette.ink,
    fontFamily: serifFont,
    fontSize: Platform.select({ ios: 24, default: 23 }),
    lineHeight: Platform.select({ ios: 30, default: 29 }),
  },
  body: {
    color: palette.body,
    fontSize: Platform.select({ ios: 17, default: 15 }),
    lineHeight: Platform.select({ ios: 22, default: 21 }),
  },
  label: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    letterSpacing: Platform.select({ ios: 1.15, default: 0 }),
    textTransform: 'uppercase',
  },
  primaryButton: {
    minHeight: 56,
    paddingHorizontal: 18,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: palette.ink,
  },
  primaryText: {
    color: palette.paper,
    fontSize: Platform.select({ ios: 17, default: 16 }),
    fontWeight: Platform.select({ ios: '600', default: '700' }),
  },
  secondaryButton: {
    minHeight: 52,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: palette.surface,
  },
  secondaryText: { color: palette.ink, fontSize: 15, fontWeight: '700' },
  disabled: { opacity: 0.42 },
  pressed: { opacity: 0.72 },
  input: {
    minHeight: 54,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 16,
    color: palette.ink,
    backgroundColor: palette.surface,
    fontSize: 16,
  },
  error: {
    padding: 18,
    borderRadius: 18,
    gap: 5,
    backgroundColor: palette.rustBackground,
  },
  errorTitle: { color: palette.rustText, fontSize: 16, fontWeight: '700' },
  errorText: { color: palette.rustText, fontSize: 14, lineHeight: 20 },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: palette.divider,
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(29, 26, 20, 0.3)',
  },
  sheet: {
    maxHeight: '90%',
    paddingTop: Platform.select({ ios: 28, default: 22 }),
    paddingHorizontal: 16,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    gap: 16,
    backgroundColor: palette.paper,
  },
  sheetHeader: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetTitle: {
    color: palette.ink,
    fontFamily: serifFont,
    fontSize: 28,
    lineHeight: 34,
  },
});
