export { JanuaryClient } from './client';
export { getNativeModuleVersion } from './native';
export { FoodCategory } from './types';
export type {
  ActivityLevel,
  AnalyzeDescriptionRequest,
  AnalyzePhotoRequest,
  AutocompleteFoodCategory,
  AutocompleteFoodsRequest,
  AutocompleteFoodsResponse,
  CorrectPhotoScanRequest,
  CreateFoodLogRequest,
  DetectedFood,
  DetectedServing,
  DietPreference,
  DietRestriction,
  FoodDetection,
  FoodLog,
  FoodLogList,
  FoodScan,
  FoodCategoryValue,
  FoodSelection,
  FoodSearchItem,
  FoodSearchResults,
  FoodSuggestion,
  GetFoodRequest,
  GetRestaurantMenuItemsRequest,
  GetRestaurantMenuItemsResponse,
  GlucosePrediction,
  GlucosePredictionPoint,
  GlucosePredictionProfile,
  JanuaryClientOptions,
  JanuaryClientToken,
  JanuaryTokenProvider,
  ListFoodLogsRequest,
  LookupFoodByBarcodeRequest,
  LoggedFood,
  MedicalCondition,
  NutrientAmount,
  NutritionFacts,
  PredictGlucoseRequest,
  Restaurant,
  RestaurantMenuEntry,
  RestaurantMenuItem,
  RestaurantResultType,
  SearchRestaurantMenuItemsResponse,
  SearchRestaurantsRequest,
  SearchRestaurantsResponse,
  SearchFoodsRequest,
  ServingDetails,
  ServingOption,
  ServingSelection,
  Sex,
  SuggestFoodAlternativesRequest,
  SuggestFoodAlternativesResponse,
  UpdateFoodLogRequest,
} from './types';
